### ISSUE TITLE
Linux / Windows: Restart sclang action gives error

### ISSUE THREAD

**Issue by chairbender** [scztt/vscode-supercollider#65]
PopOS 22.04
On this build: https://github.com/scztt/vscode-supercollider/actions/runs/12253938071 (haven't tried it on other builds)
VScode 1.98.0
SC 3.14

Selecting the "Restart sclang" action gives an error in the console: “Cannot read properties of undefined (reading ‘dispose’)” and doesn't perform the restart. Restarting the IDE and reopening the project works around this. But would be really nice to recompile without restarting the IDE!

Various other commands for this extension work fine for me.

**Comment by chairbender** [comment]
Since I'm already setup for development on this repo + the LSP, I'll go ahead and take a look at this one!

EDIT: Oops! Looks like I got sucked into the sapf project for now, so anyone else feel free to take this one on.

**Comment by scztt** [comment]
I BELIEVE I fixed this recently, you might grab the latest vsix and have a look? However, I can't easily test linux so it could still be a platform specific thing.

**Comment by chairbender** [comment]
Ah, I should've mentioned I also reproduced it on Windows. Still happening for me on Windows on the latest build (34).

**Comment by ayalavalva** [comment]
I can confirm that this issue occurs with the latest VSIX build (34).

My VSCode is running on Windows and is connected via Remote SSH to a Linux device running SuperCollider.

**Comment by chairbender** [comment]
FYI I debugged the extension locally since I realized it would probably take all of 5 minutes to figure out (meaning I shouldn't really have an excuse for not trying to fix it myself lol), and it happens in context.ts in SuperColliderContext.dispose. - `this.serverPorts` is undefined. I will submit a PR with the obvious fix but I don't have time to test super thoroughly.

**Comment by ayalavalva** [comment]
Yes, thank you @chairbender! The fix works as described!

This said, I still have a problem when evaluating `thisProcess.recompile;` which I use extensively in my startup.scd and used to work well with previous builds, but not with the latest one (34). With build 34, once evaluated, the recompile process stays stuck at:

```
*** Welcome to SuperCollider 3.14.0-dev. *** For help type ctrl-c ctrl-h (Emacs) or :SChelp (vim) or ctrl-U (sced/gedit).
***LSP READY***
```

... and then nothing happens. The workaround is to restart VSCode as for the current issue, so I am suspecting they might be related, but I can't be sure. I will open a new issue, anyway.

**Comment by scztt** [comment]
Closing this, see the comment in #67
